services:
  delay-server:
    build: ./delay-server
    networks:
      mail-1_net:
        ipv4_address: 172.21.0.2
      mail-2_net:
        ipv4_address: 172.22.0.2
    cap_add:
      - NET_ADMIN
    privileged: true

  mail-1:
    build: ./mail-server
    hostname: mail-1
    environment:
      - HOSTNAME=mail-1
      - DOMAIN=a.com
      - GATEWAY=172.21.0.2
    networks:
      mail-1_net:
        ipv4_address: 172.21.0.3
    cap_add:
      - NET_ADMIN
    ports:
      - "25:25"

  mail-2:
    build: ./mail-server
    hostname: mail-2
    environment:
      - HOSTNAME=mail-2
      - DOMAIN=a.com
      - GATEWAY=172.22.0.2
    networks:
      mail-2_net:
        ipv4_address: 172.22.0.3
    cap_add:
      - NET_ADMIN
    ports:
      - "250:25"

  mail-3:
    build: ./mail-server
    hostname: mail-3
    environment:
      - HOSTNAME=mail-3
      - DOMAIN=a.com
      - GATEWAY=172.21.0.2
      - MOZ_ENABLE_WAYLAND=1
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    volumes:
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:ro
      - /home/peanuts/Code/thunderbird-profile:/root/.thunderbird
    networks:
      mail-1_net:
        ipv4_address: 172.21.0.4
    cap_add:
      - NET_ADMIN

networks:
  mail-1_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24

  mail-2_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/24